// <auto-generated />
namespace ReverseSpectre.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class revision_of_managers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(revision_of_managers));
        
        string IMigrationMetadata.Id
        {
            get { return "201711230826559_revision_of_managers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
