// <auto-generated />
namespace ReverseSpectre.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class byte2enum_formOfBusiness : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(byte2enum_formOfBusiness));
        
        string IMigrationMetadata.Id
        {
            get { return "201711180553352_byte2enum_formOfBusiness"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
