// <auto-generated />
namespace ReverseSpectre.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class documentfile_added_TimestampCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(documentfile_added_TimestampCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201711160030444_documentfile_added_TimestampCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
