// <auto-generated />
namespace ReverseSpectre.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_comment_to_documentfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_comment_to_documentfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201711280303462_added_comment_to_documentfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
