// <auto-generated />
namespace ReverseSpectre.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class emp_info_1to1_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emp_info_1to1_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201711161851147_emp_info_1to1_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
