// <auto-generated />
namespace ReverseSpectre.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_RM_FK_to_ClientInvitation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_RM_FK_to_ClientInvitation));
        
        string IMigrationMetadata.Id
        {
            get { return "201711230837088_added_RM_FK_to_ClientInvitation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
